title: Kerameikos.org
email: gruber@numismatics.org
description: >- # this means to ignore newlines until "baseurl:"
  Kerameikos.org is a collaborative project dedicated to defining the intellectual 
  concepts of pottery following the tenets of linked open data and the formulation of 
  an ontology for representing and sharing ceramic data across disparate data systems.
baseurl: "/kerameikos" # the subpath of your site, e.g. /blog
url: "http://kerameikos.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kerameikos_org
github_username:  ewg118

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
